### PR TITLE
play-airbrake with play java

### PR DESCRIPTION
**Pull request by Enalmada**
This is what I whipped up to at least get me working.  I am sure it could be cleaned up a bit but it is a start for those that want to use play-airbrake with play java

### CODE REVIEW

**Comment by teamon** [comment]
Well, this is only readme, right?

**Comment by Enalmada** [comment]
ok, sorry about that.  Not sure how my code got in a branch before. fixed that up properly so that the code is here too

**Comment by Enalmada** [comment]
Nice!  Thanks for making this great module.  Will recommend.

**Comment by teamon** [comment]
@Enalmada :)

Btw, what is the full name of RequestHeader type in
`public Result onError(RequestHeader request, Throwable t)`
?

**Comment by Enalmada** [comment]
Good idea...it is so hard to know what things are from snippets of code:

import play.mvc.Http.RequestHeader;

**Comment by teamon** [comment]
I just checked the code, onError method in GlobalSettings has the following signature:

`onError(java.lang.Throwable t)`

no request there. Also RequestHeader is static class.

**Comment by Enalmada** [comment]
Well this is the code I am running with play 2.0.4 java and it definitely works.  The onError interface I am using might be newer than the code you are looking in? I saw import play.mvc.Http.RequestHeader in my auto-eclipse generated imports and figured that was what it was but perhaps it is something else being imported.  I will confirm tonight.

import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.concurrent.TimeUnit;

import play.Application;
import play.GlobalSettings;
import play.Logger;
import play.Play;
import play.mvc.Call;
import play.mvc.Http;
import play.mvc.Http.Context;
import play.mvc.Http.RequestHeader;
import play.mvc.Result;

public class Global extends GlobalSettings {

```
@Override
public Result onError(RequestHeader request, Throwable t) {

    // This is as close as I could come to having the same things as scala
    Map<String, String> data = new HashMap<String, String>();
    for (Entry<String, String[]> value : request.headers().entrySet()) {
        data.put(value.getKey(), Arrays.deepToString(value.getValue()));
    }

    Airbrake.notify(request.method(), request.uri(), data, t);
    return super.onError(request, t);
}
```

**Comment by Enalmada** [comment]
http://www.playframework.org/documentation/api/2.0.4/java/index.html?play/GlobalSettings.html

**Comment by Enalmada** [comment]
Http.RequestHeader is the correct one from the docs.  I should have checked the docs first!  Next time I submit code I will be explicit the first time.

**Comment by teamon** [comment]
Should be good now

**Pull request merged**
