### PR TITLE
Update Airbrake to play 2.1

### PR DESCRIPTION
**Pull request by Enalmada**
I really wanted to use Airbrake with play 2.1 so this is the code that I ended up with after much toil. 
I am not a scala programmer and play 2.1 did change exceptions stuff so I am sure this could be done better but at least it works enough in 2.1 to use and be a starting point to make it work the right way.

Thanks for all your work in making this play module.

### CODE REVIEW

**Comment by teamon** [comment]
@Enalmada Sorry it took so long. Thank you very much for your pull request! Please check play-airbrake version 0.3.0-SNAPSHOT, if everything is fine I will release 0.3.0 stable version.

**Comment by Enalmada** [comment]
Hmmm...That does not seem to be available to me....

[error](*:update) sbt.ResolveException: unresolved dependency: eu.teamon#play-a
irbrake_2.10;0.3.0-SNAPSHOT: not found

**Comment by Enalmada** [comment]
I just pasted the code directly in so I could test it out and notice that the "session data" in airbrake doesn't show the actual values like the code I posted...

{"Referer"=>"[Ljava.lang.String;@747c6d0",
 "Connection"=>"[Ljava.lang.String;@794d856b",
 "Accept"=>"[Ljava.lang.String;@50727204",
 "Accept-Charset"=>"[Ljava.lang.String;@99b8ddf",
 "Cookie"=>"[Ljava.lang.String;@437f3066",
 "Accept-Language"=>"[Ljava.lang.String;@53429b28",
 "Accept-Encoding"=>"[Ljava.lang.String;@39d889cc",
 "User-Agent"=>"[Ljava.lang.String;@373ecdbf",
 "Host"=>"[Ljava.lang.String;@7c35d2ee",
 "X-Requested-With"=>"[Ljava.lang.String;@31ab46f7"}

**Comment by teamon** [comment]
Please check now. Notice that repository has changed to repo.teamon.eu (see README for details). The version is 0.3.1-SNAPSHOT

**Comment by Enalmada** [comment]
Looks great!  Thanks for doing that.  Everyone using play should be using this.

**Pull request closed without merging**
